# Ambiente: DEV

#TEST

name: Job Parceria

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID: VALOR_INSTANCE_ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Executar Job DEV
        run: echo "Executando Job DEV com INSTANCE_ID=VALOR_INSTANCE_ID"
