# Ambiente: PROD

name: Job Parceria

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID: ${INSTANCE_ID}
      AMBIENTE: ${AMBIENTE}
      OWNER: ${OWNER}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Executar Job PROD
        run: echo "Executando Job PROD com INSTANCE_ID=${INSTANCE_ID}"
