name: DEV Implementation

on: 
  push:
    branches:
      - main

jobs:

  Deploy-DEV:

    runs-on: ubuntu-latest
    environment:
      name: dev
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get changed YAML files
      id: yaml-files
      run: |
        pip install requests
        export GH_TOKEN=${{ secrets.GH_TOKEN }}
        files=$(python trasncricao.py)
        echo "::set-output name=files::${files}"

    - name: Staging Environment Variables
      id: staging-env-vars
      uses: raven-actions/environment-variables@v1.0.0
      with:
        github-token: ${{ secrets.TESTE_TOKEN }}
        environment: dev

    - name: Replace with envsubst
      run: |
        IFS=',' read -ra yaml_files <<< "${{ steps.yaml-files.outputs.files }}"
        for file in "${yaml_files[@]}"; do
          envsubst < $file | tee $file
        done
          
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-yaml-files
        path: |
          $(for file in "${yaml_files[@]}"; do echo $file; done)
      if: success()
